platform :ios, '8.0'

target 'MyOffer' do
    pod 'IDMPhotoBrowser'
    pod 'ZFPlayer'
    pod 'MJExtension'
    pod 'SDCycleScrollView'
    pod 'MLeaksFinder'
    pod 'JPush'
    pod 'Meiqia'
#    pod 'UMCCommon'
#    pod 'UMCSecurityPlugins'
#    pod 'UMCShare/UI'
#    pod 'UMCShare/Social/ReducedWeChat'
#    pod 'UMCShare/Social/ReducedQQ'
#    pod 'UMCShare/Social/ReducedSina'
#    pod 'UMCShare/Social/Email'

end
