platform :ios, '8.0'

target 'MyOffer' do
    pod 'IDMPhotoBrowser'
    pod 'ZFPlayer'
    pod 'MJExtension'
    pod 'SDCycleScrollView'
    pod 'MLeaksFinder'
    pod 'JPush'
    pod 'SDWebImage/GIF'
    pod 'Meiqia'
    pod 'SocketRocket'
    pod 'SSZipArchive'
    pod 'Mapbox-iOS-SDK'
#    pod 'HockeySDK'
end
